apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yaml
    kompose.version: 1.35.0 (HEAD)
  labels:
    io.kompose.service: com
  name: com
spec:
  selector:
    io.kompose.service: com
    ports:
    - name: "8080"
      port: 8080
      targetPort: 8080
      nodePort: 30001
  type: NodePort
