apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yaml
    kompose.version: 1.35.0 (HEAD)
  labels:
    io.kompose.service: com
  name: com
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: com
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yaml
        kompose.version: 1.35.0 (HEAD)
      labels:
        io.kompose.service: com
    spec:
      containers:
      - name: com
        image: nginx:latest
        ports:
        - containerPort: 8080
          protocol: TCP
      restartPolicy: Always
