apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yaml
    kompose.version: 1.35.0 (HEAD)
  labels:
    io.kompose.service: drone
  name: drone
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: drone
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yaml
        kompose.version: 1.35.0 (HEAD)
      labels:
        io.kompose.service: drone
    spec:
      containers:
          name: drone
          ports:
            - containerPort: 8080
              protocol: TCP
      restartPolicy: Always
