apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yaml
    kompose.version: 1.35.0 (HEAD)
  labels:
    io.kompose.service: map
  name: map
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: map
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yaml
        kompose.version: 1.35.0 (HEAD)
      labels:
        io.kompose.service: map-ui
    spec:
      containers:
          name: map
          ports:
            - containerPort: 80
              protocol: TCP
      restartPolicy: Always
